name: Java CI with Maven

env:
  STACK: java
  CONTINUE_ON_ERROR: false
  TOMCAT_HOST: 3.134.247.4
  ARTIFACT_PATH: target/*.war
  CONTEXT_PATH: springboot
  PORT: 8080
  
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: 'Checkout repository on branch: ${{ github.REF }}'
      uses: actions/checkout@v1
      continue-on-error: ${{ env.CONTINUE_ON_ERROR }}
      with:
        ref: ${{ github.REF }}
        fetch-depth: 0
        
    - name: set up JDK 1.8
      id: setup_jdk
      if: ${{ env.STACK == 'java' }}
      uses: actions/setup-java@v1
      continue-on-error: ${{ env.CONTINUE_ON_ERROR }}
      with:
        java-version: '1.8'
    - name: Build with Maven
      run: mvn clean package --file pom.xml
      
    - name: Deploy to tomcat
      uses: appleboy/scp-action@master
      with:
        host: ${{ env.TOMCAT_HOST }}
        username: ${{ secrets.TOMCAT_USER }}
        key: ${{ secrets.SSH_KEY }}
        rm: true
        source: "${{ env.ARTIFACT_PATH }}"
        target: "${{ secrets.REMOTE_DIR }}/"    
